In [1]:
import numpy as np

# Mean Squared Error (MSE)
def mean_squared_error(y_true, y_pred):
    return np.mean(np.square(y_true - y_pred))

# Binary Cross-Entropy (BinaryCE)
def binary_cross_entropy(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)  # Avoid log(0)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Categorical Cross-Entropy (CategoricalCE)
def categorical_cross_entropy(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)  # Avoid log(0)
    return -np.mean(y_true * np.log(y_pred))


In [8]:

# Example usage
# Assuming ground truth and predicted values
y_true_regression = np.array([2, 3, 4, 5])
y_pred_regression = np.array([1.8, 3.2, 3.7, 5.2])

y_true_binary = np.array([0, 1, 1, 0])
y_pred_binary = np.array([0.1, 0.9, 0.8, 0.2])

y_true_categorical = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
y_pred_categorical = np.array([[0.2, 0.7, 0.1], [0.8, 0.1, 0.1], [0.1, 0.2, 0.7]])

print("y_true_regression :\n",y_true_regression)
print("y_pred_regression :\n",y_pred_regression)

print("y_true_binary :\n",y_true_binary)
print("y_pred_binary :\n",y_pred_binary)

print("y_true_categorical :\n",y_true_categorical)
print("y_pred_categorical :\n",y_pred_categorical)


y_true_regression :
 [2 3 4 5]
y_pred_regression :
 [1.8 3.2 3.7 5.2]
y_true_binary :
 [0 1 1 0]
y_pred_binary :
 [0.1 0.9 0.8 0.2]
y_true_categorical :
 [[0 1 0]
 [1 0 0]
 [0 0 1]]
y_pred_categorical :
 [[0.2 0.7 0.1]
 [0.8 0.1 0.1]
 [0.1 0.2 0.7]]


In [9]:

# Calculate losses
mse_loss = mean_squared_error(y_true_regression, y_pred_regression)
binary_ce_loss = binary_cross_entropy(y_true_binary, y_pred_binary)
categorical_ce_loss = categorical_cross_entropy(y_true_categorical, y_pred_categorical)

# Print losses
print("Mean Squared Error (MSE):", mse_loss)
print("Binary Cross-Entropy (BinaryCE):", binary_ce_loss)
print("Categorical Cross-Entropy (CategoricalCE):", categorical_ce_loss)


Mean Squared Error (MSE): 0.0525
Binary Cross-Entropy (BinaryCE): 0.164252033486018
Categorical Cross-Entropy (CategoricalCE): 0.10405482657685274
